services:
  klarvpn-shop:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: klarvpn-shop
    hostname: klarvpn-shop
    env_file:
      - .env
    networks:
      - remnawave-network
    volumes:
      - ./locales:/app/locales
    restart: unless-stopped
    depends_on:
      klarvpn-shop-db:
        condition: service_healthy

  klarvpn-shop-db:
    image: postgres:18-alpine
    container_name: ${DATABASE_HOST:-klarvpn-shop-db}
    restart: always
    ports:
      - "${DATABASE_PORT:-5432}:${DATABASE_PORT:-5432}"
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      PGPORT: ${DATABASE_PORT:-5432}
      TZ: UTC
    command:
      - -p
      - "${DATABASE_PORT:-5432}"
    env_file:
      - .env
    volumes:
      - klarvpn-shop-db-data:/var/lib/postgresql/data
    networks:
      - remnawave-network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME} -p ${DATABASE_PORT:-5432}",
        ]
      interval: 3s
      timeout: 10s
      retries: 3

  klarvpn-shop-redis:
    image: valkey/valkey:8.1-alpine
    container_name: ${REDIS_HOST:-klarvpn-shop-redis}
    ports:
      - "${REDIS_PORT:-6379}:${REDIS_PORT:-6379}"
    command:
      - valkey-server
      - --port
      - "${REDIS_PORT:-6379}"
      - --requirepass
      - "${REDIS_PASSWORD}"
      - --save
      - ""
    restart: always
    networks:
      - remnawave-network
    volumes:
      - klarvpn-shop-redis-data:/data
    healthcheck:
      test:
        [
          "CMD",
          "valkey-cli",
          "-p",
          "${REDIS_PORT:-6379}",
          "-a",
          "${REDIS_PASSWORD}",
          "ping",
        ]
      interval: 3s
      timeout: 10s
      retries: 3

networks:
  remnawave-network: null

volumes:
  klarvpn-shop-db-data:
    name: klarvpn-shop-database-data
  klarvpn-shop-redis-data:
    name: klarvpn-shop-redis-data
